name: build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      singlestore:
        # check for new versions at https://hub.docker.com/r/singlestore/cluster-in-a-box/tags
        image: singlestore/cluster-in-a-box:alma-7.8.2-8c7b918527-4.0.5-1.13.6
        ports:
          - "3306:3306"
        env:
          LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "test"
          START_AFTER_INIT: "Y"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: build
        run: go build s2kv/cmd/s2kv
      - name: install go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest
      - name: wait for singlestore to start
        run: |
          until mysql -h 127.0.0.1 -u root -ptest -e "select 1"; do
            echo "waiting for mysql..."
            sleep 1
          done
      - name: singlestore container logs
        run: docker logs $(docker ps -ql)
      - name: setup schema
        run: |
          mysql -h 127.0.0.1 -u root -ptest -e "create database kv"
          mysql -h 127.0.0.1 -u root -ptest kv <schema.sql
          mysql -h 127.0.0.1 -u root -ptest kv <procedures.sql
      - name: run tests
        run: go test -v -config config.github.toml 2>&1 ./... | go-junit-report -set-exit-code >report.xml
      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "report.xml"
